[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.localnet]
cardinal_stake_pool = "HLstk9rqdV3ADMKdayqVTivmiCsUrA54YjEVK3tQEbj6"
cardinal_reward_distributor = "BfG2CLmVqKDM7RLLw9QvyZo4FzJt5XR3hVK7KQ36FPD4"
cardinal_receipt_manager = "4cJvYVJAgeJ8v5XfmLbGdTLM4kfGfB8pUk1912yvj4z4"

[programs.devnet]
cardinal_stake_pool = "HLstk9rqdV3ADMKdayqVTivmiCsUrA54YjEVK3tQEbj6"
cardinal_reward_distributor = "BfG2CLmVqKDM7RLLw9QvyZo4FzJt5XR3hVK7KQ36FPD4"
cardinal_receipt_manager = "4cJvYVJAgeJ8v5XfmLbGdTLM4kfGfB8pUk1912yvj4z4"

[programs.mainnet]
cardinal_stake_pool = "HLstk9rqdV3ADMKdayqVTivmiCsUrA54YjEVK3tQEbj6"
cardinal_reward_distributor = "BfG2CLmVqKDM7RLLw9QvyZo4FzJt5XR3hVK7KQ36FPD4"
cardinal_receipt_manager = "4cJvYVJAgeJ8v5XfmLbGdTLM4kfGfB8pUk1912yvj4z4"

[scripts]
test-dev-all = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests.ts"
test-dev = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests-hl.ts"
test-pro = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests-hl-pro.ts"

[provider]
# cluster = "devnet"
# cluster = "https://frosty-floral-wind.solana-devnet.quiknode.pro/fa3c7dec03be0b5335ff2905b342eedf94ada834/"
# wallet = "/home/setmax/.config/solana/devnet.json"

cluster = "mainnet"
# cluster = "https://delicate-dark-rain.solana-mainnet.quiknode.pro/4bc3650ce97395e47b05a0177dc7b7dbc7f886a0/"
wallet = "/home/setmax/.config/solana/main_wallets/hl_upgrade_auth.json"


#cluster = "localnet"
#wallet = "/home/setmax/.config/solana/id.json"
# cluster = "http://127.0.0.1:8899"
# wallet = "/home/setmax/.config/solana/localnet.json"
