[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[programs.localnet]
honeyland_staking_contract = "D7scofMhczWugX7WZPXSP3YjjSyDijEULpwQdraVj54q"


[programs.devnet]
honeyland_staking_contract = "HLstk9rqdV3ADMKdayqVTivmiCsUrA54YjEVK3tQEbj6"


[programs.mainnet]
honeyland_staking_contract = "HLstk9rqdV3ADMKdayqVTivmiCsUrA54YjEVK3tQEbj6"

[scripts]
test-dev-all = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests.ts"
test-dev = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests-hl.ts"
test-pro = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests-hl-pro.ts"

[provider]
# cluster = "devnet"
# cluster = "https://frosty-floral-wind.solana-devnet.quiknode.pro/fa3c7dec03be0b5335ff2905b342eedf94ada834/"
# wallet = "/home/setmax/.config/solana/devnet.json"

cluster = "localnet"
# cluster = "https://delicate-dark-rain.solana-mainnet.quiknode.pro/4bc3650ce97395e47b05a0177dc7b7dbc7f886a0/"
wallet = "/home/bamdad/.config/solana/id.json"


#cluster = "localnet"
#wallet = "/home/setmax/.config/solana/id.json"
# cluster = "http://127.0.0.1:8899"
# wallet = "/home/setmax/.config/solana/localnet.json"
