[features]
seeds = false
skip-lint = false

[programs.localnet]
cardinal_stake_pool = "73QM3VFNvtS2k5KJ3zH8RvkR4ri9gQaE1f4t1dnPNmSA"
cardinal_reward_distributor = "E2z64E5B64qvpsbArf9AE3m8vhAazqXh4FmiRKp1aKSt"
cardinal_receipt_manager = "EmMEf6vBxFhyeDR6Q8BXNB3734LxufxEE8JbUMmiSPGC"
[programs.devnet]
cardinal_stake_pool = "73QM3VFNvtS2k5KJ3zH8RvkR4ri9gQaE1f4t1dnPNmSA"
cardinal_reward_distributor = "E2z64E5B64qvpsbArf9AE3m8vhAazqXh4FmiRKp1aKSt"
cardinal_receipt_manager = "EmMEf6vBxFhyeDR6Q8BXNB3734LxufxEE8JbUMmiSPGC"

[scripts]
test-local = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/tests.ts"

[provider]
cluster = "devnet"
wallet = "/home/bamdad/.config/solana/id.json"

# [programs.mainnet]
# cardinal_stake_pool = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
# cardinal_reward_distributor = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
# cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

# [programs.devnet]
# cardinal_stake_pool = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
# cardinal_reward_distributor = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
# cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

# [programs.testnet]
# cardinal_stake_pool = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
# cardinal_reward_distributor = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
# cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

